#!/usr/bin/env bash
set -Eeuo pipefail

# OCI Cloud Shell quick start:
# 1. Edit exadb_dr_network.conf in this same folder.
# 2. Run ./setup_exadb_dr_network.sh
# 3. Review exadb_dr_network.log and the generated exadb_dr_network_state_<timestamp>.env
#
# Manual verification checklist:
# - LPG peering in the primary region is PEERED.
# - LPG peering in the standby region is PEERED.
# - DRG RPC peering across regions is PEERED.
# - Existing Exadata VCN route tables point remote client/backup CIDRs to the local LPG.
# - Hub DRG attachment route tables point local client/backup CIDRs to the hub LPG.
# - Hub LPG route tables point remote client/backup CIDRs to the local DRG.
# - RPC DRG route tables point local client/backup CIDRs to the local hub VCN attachment.
# - NSGs exist in both Exadata VCNs.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${1:-$SCRIPT_DIR/exadb_dr_network.conf}"
LOG_FILE="$SCRIPT_DIR/exadb_dr_network.log"
RUN_TS="$(date -u +%Y%m%dT%H%M%SZ)"
STATE_FILE="$SCRIPT_DIR/exadb_dr_network_state_${RUN_TS}.env"
BUNDLE_VERSION="2026-03-16-parallel-regions-v1"
NAME_PREFIX_DEFAULT="exadb-dr-network"
DESCRIPTION_TOKEN=""
TMP_FILES=()
RPC_PEERING_PID=""
RPC_PEERING_STATUS_FILE=""

export OCI_CLI_SUPPRESS_FILE_PERMISSIONS_WARNING=True

touch "$LOG_FILE"

on_error() {
  local exit_code="$?"
  local line_no="${1:-unknown}"
  local cmd="${2:-unknown}"
  printf '%s [%s] Unexpected failure at line %s while running: %s\n' \
    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "ERROR" "$line_no" "$cmd" | tee -a "$LOG_FILE" >&2
  exit "$exit_code"
}

trap 'on_error "$LINENO" "$BASH_COMMAND"' ERR

log() {
  local level="$1"
  shift
  printf '%s [%s] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$level" "$*" | tee -a "$LOG_FILE"
}

fail() {
  log "ERROR" "$*"
  exit 1
}

cleanup_tmp() {
  if ((${#TMP_FILES[@]} > 0)); then
    rm -f "${TMP_FILES[@]}"
  fi
}

trap cleanup_tmp EXIT

require_cmd() {
  local cmd="$1"
  command -v "$cmd" >/dev/null 2>&1 || fail "Required command not found: $cmd"
}

make_tmp_json() {
  local tmp
  tmp="$(mktemp "$SCRIPT_DIR/exadb_dr_network_tmp_XXXXXX.json")"
  TMP_FILES+=("$tmp")
  printf '%s\n' "$tmp"
}

make_tmp_env() {
  local tmp
  tmp="$(mktemp "$SCRIPT_DIR/exadb_dr_network_tmp_XXXXXX.env")"
  TMP_FILES+=("$tmp")
  printf '%s\n' "$tmp"
}

persist_state_header() {
  cat >"$STATE_FILE" <<EOF
#!/usr/bin/env bash
# Generated by setup_exadb_dr_network.sh on ${RUN_TS}
# Source this file only for rollback automation.
EOF
}

persist_state() {
  local key="$1"
  local value="${2-}"
  printf '%s=%q\n' "$key" "$value" >>"$STATE_FILE"
}

normalize_bool() {
  local value="${1:-false}"
  case "${value,,}" in
    true|false) printf '%s\n' "${value,,}" ;;
    *) fail "ALLOW_SSH must be true or false, got: $value" ;;
  esac
}

normalize_port_or_empty() {
  local value="${1:-}"
  [[ -n "$value" ]] || { printf '\n'; return 0; }
  [[ "$value" =~ ^[0-9]+$ ]] || fail "Listener port must be a number, got: $value"
  ((value >= 1 && value <= 65535)) || fail "Listener port must be between 1 and 65535, got: $value"
  printf '%s\n' "$value"
}

sanitize_name_prefix() {
  local raw="${1:-$NAME_PREFIX_DEFAULT}"
  raw="$(printf '%s' "$raw" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9-' '-')"
  raw="${raw##-}"
  raw="${raw%%-}"
  [[ -n "$raw" ]] || raw="$NAME_PREFIX_DEFAULT"
  printf '%s\n' "$raw"
}

oci_json() {
  local region="$1"
  shift
  oci --region "$region" "$@" --output json
}

oci_raw() {
  local region="$1"
  shift
  oci --region "$region" "$@" --raw-output
}

json_query_arg() {
  local json_input="$1"
  local py_code="$2"
  shift 2
  python3 -c "$py_code" "$json_input" "$@"
}

cidr_overlap_check() {
  local candidate="$1"
  shift
  python3 -c 'import ipaddress, json, sys
candidate = ipaddress.ip_network(sys.argv[1], strict=False)
for raw in sys.argv[2:]:
    if not raw:
        continue
    for entry in json.loads(raw):
        if not entry:
            continue
        if candidate.overlaps(ipaddress.ip_network(entry, strict=False)):
            raise SystemExit(1)
raise SystemExit(0)
' "$candidate" "$@"
}

resolve_hub_vcn_cidrs() {
  local primary_vcn_cidrs_json="$1"
  local standby_vcn_cidrs_json="$2"
  local configured_primary="${3:-}"
  local configured_standby="${4:-}"
  local base_json
  local candidates=(
    "172.31.240.0/29"
    "172.31.241.0/29"
    "172.31.242.0/29"
    "172.31.243.0/29"
    "172.31.244.0/29"
    "172.31.245.0/29"
    "172.31.246.0/29"
    "172.31.247.0/29"
    "172.31.248.0/29"
    "172.31.249.0/29"
  )
  local primary="$configured_primary"
  local standby="$configured_standby"
  local candidate

  base_json="$(python3 -c 'import json, sys
items = []
for raw in sys.argv[1:]:
    if not raw:
        continue
    items.extend([entry for entry in json.loads(raw) if entry])
print(json.dumps(items))' \
    "$primary_vcn_cidrs_json" \
    "$standby_vcn_cidrs_json")"

  if [[ -n "$primary" ]] && ! cidr_overlap_check "$primary" "$base_json"; then
    fail "Configured PRIMARY_HUB_VCN_CIDR $primary overlaps with an existing primary or standby VCN CIDR."
  fi

  if [[ -n "$standby" ]] && ! cidr_overlap_check "$standby" "$base_json"; then
    fail "Configured STANDBY_HUB_VCN_CIDR $standby overlaps with an existing primary or standby VCN CIDR."
  fi

  if [[ -n "$primary" && -n "$standby" ]]; then
    if ! cidr_overlap_check "$primary" "$(python3 -c 'import json, sys; print(json.dumps([sys.argv[1]]))' "$standby")"; then
      fail "Configured PRIMARY_HUB_VCN_CIDR $primary overlaps with STANDBY_HUB_VCN_CIDR $standby."
    fi
    printf '%s\n%s\n' "$primary" "$standby"
    return 0
  fi

  if [[ -n "$primary" ]]; then
    base_json="$(python3 -c 'import json, sys; items=json.loads(sys.argv[1]); items.append(sys.argv[2]); print(json.dumps(items))' "$base_json" "$primary")"
  fi
  if [[ -n "$standby" ]]; then
    base_json="$(python3 -c 'import json, sys; items=json.loads(sys.argv[1]); items.append(sys.argv[2]); print(json.dumps(items))' "$base_json" "$standby")"
  fi

  if [[ -z "$primary" ]]; then
    for candidate in "${candidates[@]}"; do
      if cidr_overlap_check "$candidate" "$base_json"; then
        primary="$candidate"
        base_json="$(python3 -c 'import json, sys; items=json.loads(sys.argv[1]); items.append(sys.argv[2]); print(json.dumps(items))' "$base_json" "$primary")"
        break
      fi
    done
    [[ -n "$primary" ]] || fail "Could not auto-pick PRIMARY_HUB_VCN_CIDR. Set it explicitly in exadb_dr_network.conf."
  fi

  if [[ -z "$standby" ]]; then
    for candidate in "${candidates[@]}"; do
      if cidr_overlap_check "$candidate" "$base_json"; then
        standby="$candidate"
        break
      fi
    done
    [[ -n "$standby" ]] || fail "Could not auto-pick STANDBY_HUB_VCN_CIDR. Set it explicitly in exadb_dr_network.conf."
  fi

  printf '%s\n%s\n' "$primary" "$standby"
}

wait_for_field() {
  local region="$1"
  local kind="$2"
  local ocid="$3"
  local field="$4"
  local expected="$5"
  local attempts="${6:-30}"
  local delay="${7:-10}"
  local get_cmd=()
  local current=""
  local attempt

  case "$kind" in
    vcn) get_cmd=(network vcn get --vcn-id "$ocid") ;;
    lpg) get_cmd=(network local-peering-gateway get --local-peering-gateway-id "$ocid") ;;
    drg) get_cmd=(network drg get --drg-id "$ocid") ;;
    rpc) get_cmd=(network remote-peering-connection get --remote-peering-connection-id "$ocid") ;;
    drg-attachment) get_cmd=(network drg-attachment get --drg-attachment-id "$ocid") ;;
    *) fail "Unsupported wait_for_field kind: $kind" ;;
  esac

  for ((attempt = 1; attempt <= attempts; attempt++)); do
    current="$(oci_raw "$region" "${get_cmd[@]}" --query "data.\"$field\"" 2>/dev/null || true)"
    if [[ "$current" == "$expected" ]]; then
      return 0
    fi
    sleep "$delay"
  done

  fail "Timed out waiting for $kind $ocid field $field to become $expected. Last value: ${current:-unknown}"
}

wait_for_attachment_route_table() {
  local region="$1"
  local drg_attachment_id="$2"
  local expected_route_table_id="$3"
  local attempts="${4:-30}"
  local delay="${5:-10}"
  local current=""
  local attempt

  for ((attempt = 1; attempt <= attempts; attempt++)); do
    current="$(oci_raw "$region" network drg-attachment get --drg-attachment-id "$drg_attachment_id" --query 'data."route-table-id"' 2>/dev/null || true)"
    if [[ "$current" == "$expected_route_table_id" ]]; then
      return 0
    fi
    sleep "$delay"
  done

  fail "Timed out waiting for DRG attachment $drg_attachment_id to use VCN route table $expected_route_table_id. Last value: ${current:-unknown}"
}

append_unique_word() {
  local current="${1-}"
  local new_word="$2"
  local word
  for word in $current; do
    if [[ "$word" == "$new_word" ]]; then
      printf '%s\n' "$current"
      return 0
    fi
  done
  if [[ -n "$current" ]]; then
    printf '%s %s\n' "$current" "$new_word"
  else
    printf '%s\n' "$new_word"
  fi
}

discover_subnet() {
  local region="$1"
  local compartment_id="$2"
  local vcn_id="$3"
  local cidr="$4"
  local label="$5"
  local subnet_json
  subnet_json="$(oci_json "$region" network subnet list --compartment-id "$compartment_id" --vcn-id "$vcn_id" --all)"

  json_query_arg "$subnet_json" 'import json, sys
payload = json.loads(sys.argv[1])
cidr = sys.argv[2]
label = sys.argv[3]
matches = [item for item in payload.get("data", []) if item.get("cidr-block") == cidr]
if not matches:
    raise SystemExit(f"Missing required {label} subnet with CIDR {cidr}")
if len(matches) != 1:
    raise SystemExit(f"Ambiguous {label} subnet lookup for CIDR {cidr}: found {len(matches)} matches")
item = matches[0]
print(item["id"])
print(item["route-table-id"])
print(item.get("display-name", ""))
' "$cidr" "$label"
}

route_rules_merged_file() {
  local current_rules_json="$1"
  local destination="$2"
  local network_entity_id="$3"
  local description="$4"
  local out_file="$5"
  python3 -c 'import json, sys
rules = json.loads(sys.argv[1])
destination = sys.argv[2]
entity = sys.argv[3]
description = sys.argv[4]
out_file = sys.argv[5]
exists = any(item.get("destination") == destination and item.get("network-entity-id") == entity for item in rules)
if not exists:
    rules.append({
        "description": description,
        "destination": destination,
        "destination-type": "CIDR_BLOCK",
        "network-entity-id": entity
    })
with open(out_file, "w", encoding="utf-8") as handle:
    json.dump(rules, handle, indent=2, sort_keys=True)
' "$current_rules_json" "$destination" "$network_entity_id" "$description" "$out_file"
}

update_route_table_add_rule() {
  local region="$1"
  local route_table_id="$2"
  local destination="$3"
  local network_entity_id="$4"
  local description="$5"
  local current_rules_json
  local merged_file

  current_rules_json="$(oci_json "$region" network route-table get --rt-id "$route_table_id" --query 'data."route-rules"')"
  merged_file="$(make_tmp_json)"
  route_rules_merged_file "$current_rules_json" "$destination" "$network_entity_id" "$description" "$merged_file"
  oci --region "$region" network route-table update --rt-id "$route_table_id" --route-rules "file://$merged_file" --force >/dev/null
}

create_nsg_rules_file() {
  local remote_client_cidr="$1"
  local remote_backup_cidr="$2"
  local allow_ssh="$3"
  local tcp_listener_port="$4"
  local tcps_listener_port="$5"
  local out_file="$6"
  python3 -c 'import json, sys
remote_client = sys.argv[1]
remote_backup = sys.argv[2]
allow_ssh = sys.argv[3] == "true"
tcp_listener_port = sys.argv[4]
tcps_listener_port = sys.argv[5]
out_file = sys.argv[6]
cidrs = [remote_client, remote_backup]
oracle_ports = []
if tcp_listener_port:
    oracle_ports.append(int(tcp_listener_port))
if tcps_listener_port:
    oracle_ports.append(int(tcps_listener_port))
rules = []
for cidr in cidrs:
    for port in oracle_ports:
        rules.append({
            "direction": "INGRESS",
            "is-stateless": False,
            "protocol": "6",
            "source": cidr,
            "source-type": "CIDR_BLOCK",
            "tcp-options": {"destination-port-range": {"min": port, "max": port}},
            "description": f"Allow Oracle Net ingress from {cidr} to port {port}"
        })
        rules.append({
            "direction": "EGRESS",
            "is-stateless": False,
            "protocol": "6",
            "destination": cidr,
            "destination-type": "CIDR_BLOCK",
            "tcp-options": {"destination-port-range": {"min": port, "max": port}},
            "description": f"Allow Oracle Net egress to {cidr} on port {port}"
        })
if allow_ssh:
    for cidr in cidrs:
        rules.append({
            "direction": "INGRESS",
            "is-stateless": False,
            "protocol": "6",
            "source": cidr,
            "source-type": "CIDR_BLOCK",
            "tcp-options": {"destination-port-range": {"min": 22, "max": 22}},
            "description": f"Allow SSH ingress from {cidr}"
        })
        rules.append({
            "direction": "EGRESS",
            "is-stateless": False,
            "protocol": "6",
            "destination": cidr,
            "destination-type": "CIDR_BLOCK",
            "tcp-options": {"destination-port-range": {"min": 22, "max": 22}},
            "description": f"Allow SSH egress to {cidr}"
        })
with open(out_file, "w", encoding="utf-8") as handle:
    json.dump(rules, handle, indent=2, sort_keys=True)
' "$remote_client_cidr" "$remote_backup_cidr" "$allow_ssh" "$tcp_listener_port" "$tcps_listener_port" "$out_file"
}

create_drg_attachment_payload() {
  local vcn_id="$1"
  local out_file="$2"
  python3 -c 'import json, sys
payload = {"id": sys.argv[1], "type": "VCN"}
with open(sys.argv[2], "w", encoding="utf-8") as handle:
    json.dump(payload, handle, indent=2, sort_keys=True)
' "$vcn_id" "$out_file"
}

create_drg_route_rule_payload() {
  local destination="$1"
  local next_hop_attachment_id="$2"
  local out_file="$3"
  python3 -c 'import json, sys
payload = [{
    "destination": sys.argv[1],
    "destinationType": "CIDR_BLOCK",
    "nextHopDrgAttachmentId": sys.argv[2]
}]
with open(sys.argv[3], "w", encoding="utf-8") as handle:
    json.dump(payload, handle, indent=2, sort_keys=True)
' "$destination" "$next_hop_attachment_id" "$out_file"
}

drg_route_rule_exists() {
  local region="$1"
  local drg_route_table_id="$2"
  local destination="$3"
  local next_hop_attachment_id="$4"
  local rules_json
  rules_json="$(oci_json "$region" network drg-route-rule list --drg-route-table-id "$drg_route_table_id" --all)"
  python3 -c 'import json, sys
payload = json.loads(sys.argv[1])
destination = sys.argv[2]
next_hop = sys.argv[3]
items = payload.get("data", payload if isinstance(payload, list) else [])
for item in items:
    if item.get("destination") == destination and item.get("next-hop-drg-attachment-id") == next_hop:
        raise SystemExit(0)
raise SystemExit(1)
' "$rules_json" "$destination" "$next_hop_attachment_id"
}

update_drg_route_table_add_rule() {
  local region="$1"
  local drg_route_table_id="$2"
  local destination="$3"
  local next_hop_attachment_id="$4"
  local payload_file
  if drg_route_rule_exists "$region" "$drg_route_table_id" "$destination" "$next_hop_attachment_id"; then
    return 0
  fi
  payload_file="$(make_tmp_json)"
  create_drg_route_rule_payload "$destination" "$next_hop_attachment_id" "$payload_file"
  oci --region "$region" network drg-route-rule add \
    --drg-route-table-id "$drg_route_table_id" \
    --route-rules "file://$payload_file" >/dev/null
}

validate_vcn_belongs_to_compartment() {
  local region="$1"
  local vcn_id="$2"
  local expected_compartment_id="$3"
  local label="$4"
  local actual_compartment_id
  actual_compartment_id="$(oci_raw "$region" network vcn get --vcn-id "$vcn_id" --query 'data."compartment-id"' 2>/dev/null || true)"
  [[ -n "$actual_compartment_id" ]] || fail "Configured $label VCN does not exist or is not accessible: $vcn_id"
  [[ "$actual_compartment_id" == "$expected_compartment_id" ]] || fail "Configured $label VCN $vcn_id is in compartment $actual_compartment_id, expected $expected_compartment_id"
}

load_config() {
  [[ -f "$CONFIG_FILE" ]] || fail "Config file not found: $CONFIG_FILE"
  local config_exports
  if ! config_exports="$(
    python3 -c 'import configparser, shlex, sys
config = configparser.ConfigParser()
config.optionxform = str
if not config.read(sys.argv[1]):
    raise SystemExit(f"Could not read config file: {sys.argv[1]}")
def normalize(value):
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"\x27":
        value = value[1:-1]
    return value.strip()
for section in config.sections():
    for key, value in config.items(section):
        print(f"{key}={shlex.quote(normalize(value))}")
' "$CONFIG_FILE" 2>&1
  )"; then
    fail "Failed to parse config file $CONFIG_FILE: $config_exports"
  fi
  eval "$config_exports"
}

validate_required_config() {
  local required_vars=(
    PRIMARY_REGION PRIMARY_COMPARTMENT_OCID PRIMARY_VCN_OCID PRIMARY_CLIENT_SUBNET_CIDR PRIMARY_BACKUP_SUBNET_CIDR
    STANDBY_REGION STANDBY_COMPARTMENT_OCID STANDBY_VCN_OCID STANDBY_CLIENT_SUBNET_CIDR STANDBY_BACKUP_SUBNET_CIDR
  )
  local var_name
  for var_name in "${required_vars[@]}"; do
    [[ -n "${!var_name:-}" ]] || fail "Required config value is missing: $var_name"
  done
  [[ "$PRIMARY_REGION" != "$STANDBY_REGION" ]] || fail "PRIMARY_REGION and STANDBY_REGION must be different."
}

rpc_is_peered_with_expected_peer() {
  local region="$1"
  local rpc_id="$2"
  local expected_peer_id="$3"
  local expected_peer_region="$4"
  local status
  local peer_id
  local peer_region
  status="$(oci_raw "$region" network remote-peering-connection get --remote-peering-connection-id "$rpc_id" --query 'data."peering-status"' 2>/dev/null || true)"
  peer_id="$(oci_raw "$region" network remote-peering-connection get --remote-peering-connection-id "$rpc_id" --query 'data."peer-id"' 2>/dev/null || true)"
  peer_region="$(oci_raw "$region" network remote-peering-connection get --remote-peering-connection-id "$rpc_id" --query 'data."peer-region-name"' 2>/dev/null || true)"
  [[ "$status" == "PEERED" && "$peer_id" == "$expected_peer_id" && "$peer_region" == "$expected_peer_region" ]]
}

wait_for_rpc_peer_details() {
  local region="$1"
  local rpc_id="$2"
  local expected_peer_id="$3"
  local expected_peer_region="$4"
  local attempts="${5:-18}"
  local delay="${6:-5}"
  local attempt
  for ((attempt = 1; attempt <= attempts; attempt++)); do
    if rpc_is_peered_with_expected_peer "$region" "$rpc_id" "$expected_peer_id" "$expected_peer_region"; then
      return 0
    fi
    sleep "$delay"
  done
  return 1
}

connect_rpc_pair() {
  local requestor_region="$1"
  local requestor_rpc_id="$2"
  local acceptor_region="$3"
  local acceptor_rpc_id="$4"
  log "INFO" "Connecting RPC $requestor_rpc_id in $requestor_region to RPC $acceptor_rpc_id in $acceptor_region."
  oci --region "$requestor_region" network remote-peering-connection connect \
    --remote-peering-connection-id "$requestor_rpc_id" \
    --peer-id "$acceptor_rpc_id" \
    --peer-region-name "$acceptor_region" >/dev/null
}

ensure_rpc_peering() {
  local primary_region="$1"
  local primary_rpc_id="$2"
  local standby_region="$3"
  local standby_rpc_id="$4"
  connect_rpc_pair "$primary_region" "$primary_rpc_id" "$standby_region" "$standby_rpc_id"
  wait_for_field "$primary_region" "rpc" "$primary_rpc_id" "peering-status" "PEERED"
  wait_for_field "$standby_region" "rpc" "$standby_rpc_id" "peering-status" "PEERED"
  if wait_for_rpc_peer_details "$primary_region" "$primary_rpc_id" "$standby_rpc_id" "$standby_region" &&
     wait_for_rpc_peer_details "$standby_region" "$standby_rpc_id" "$primary_rpc_id" "$primary_region"; then
    return 0
  fi
  fail "RPCs reached PEERED state but peer metadata did not converge as expected. Primary RPC: $primary_rpc_id. Standby RPC: $standby_rpc_id."
}

start_rpc_peering_background() {
  local primary_region="$1"
  local primary_rpc_id="$2"
  local standby_region="$3"
  local standby_rpc_id="$4"
  local status_file
  status_file="$(make_tmp_env)"
  RPC_PEERING_STATUS_FILE="$status_file"
  (
    set +e
    ensure_rpc_peering "$primary_region" "$primary_rpc_id" "$standby_region" "$standby_rpc_id"
    printf '%s\n' "$?" >"$status_file"
  ) &
  RPC_PEERING_PID="$!"
  log "INFO" "Started background RPC peering monitor with PID $RPC_PEERING_PID."
}

wait_for_rpc_peering_background() {
  local status
  [[ -n "${RPC_PEERING_PID:-}" ]] || fail "Internal error: RPC peering background PID is not set."
  log "INFO" "Waiting for background RPC peering task to finish."
  wait "$RPC_PEERING_PID" || true
  [[ -f "$RPC_PEERING_STATUS_FILE" ]] || fail "Background RPC peering status file was not created: $RPC_PEERING_STATUS_FILE"
  status="$(tr -d '[:space:]' <"$RPC_PEERING_STATUS_FILE")"
  [[ "$status" == "0" ]] || fail "Background RPC peering task failed with exit code ${status:-unknown}."
  log "INFO" "Background RPC peering task finished successfully."
}

verify_rpc_belongs_to_expected_drg() {
  local region="$1"
  local rpc_id="$2"
  local expected_drg_id="$3"
  local label="$4"
  local actual_drg_id
  local lifecycle_state
  actual_drg_id="$(oci_raw "$region" network remote-peering-connection get --remote-peering-connection-id "$rpc_id" --query 'data."drg-id"')"
  lifecycle_state="$(oci_raw "$region" network remote-peering-connection get --remote-peering-connection-id "$rpc_id" --query 'data."lifecycle-state"')"
  [[ "$actual_drg_id" == "$expected_drg_id" ]] || fail "The $label RPC $rpc_id is attached to DRG $actual_drg_id, expected $expected_drg_id."
  [[ "$lifecycle_state" == "AVAILABLE" ]] || fail "The $label RPC $rpc_id is not AVAILABLE. Current lifecycle state: $lifecycle_state"
}

find_rpc_drg_attachment() {
  local region="$1"
  local compartment_id="$2"
  local drg_id="$3"
  local rpc_id="$4"
  local label="$5"
  local attachment_json
  attachment_json="$(oci_json "$region" network drg-attachment list \
    --compartment-id "$compartment_id" \
    --drg-id "$drg_id" \
    --attachment-type REMOTE_PEERING_CONNECTION \
    --all)"
  json_query_arg "$attachment_json" 'import json, sys
payload = json.loads(sys.argv[1])
rpc_id = sys.argv[2]
label = sys.argv[3]
items = payload.get("data", [])
matches = []
for item in items:
    network_details = item.get("network-details", item.get("networkDetails", {}))
    network_id = (
        item.get("network-id")
        or item.get("networkId")
        or network_details.get("id")
        or network_details.get("network-id")
        or network_details.get("networkId")
    )
    lifecycle_state = item.get("lifecycle-state", item.get("lifecycleState", ""))
    if network_id == rpc_id and lifecycle_state in ("ATTACHED", "AVAILABLE", ""):
        matches.append(item)
if not matches:
    raise SystemExit(f"Could not find autogenerated RPC DRG attachment for {label} RPC {rpc_id}")
if len(matches) != 1:
    raise SystemExit(f"Ambiguous autogenerated RPC DRG attachment lookup for {label} RPC {rpc_id}: found {len(matches)} matches")
item = matches[0]
attachment_id = item.get("id", "")
drg_route_table_id = item.get("drg-route-table-id", item.get("drgRouteTableId", ""))
if not attachment_id or not drg_route_table_id:
    raise SystemExit(f"Autogenerated RPC DRG attachment for {label} RPC {rpc_id} is missing attachment metadata")
print(attachment_id)
print(drg_route_table_id)
' "$rpc_id" "$label"
}

wait_for_rpc_attachment_to_drg() {
  local region="$1"
  local compartment_id="$2"
  local drg_id="$3"
  local rpc_id="$4"
  local label="$5"
  local attempts="${6:-24}"
  local delay="${7:-5}"
  local attempt
  local attachment_output
  for ((attempt = 1; attempt <= attempts; attempt++)); do
    attachment_output="$(find_rpc_drg_attachment "$region" "$compartment_id" "$drg_id" "$rpc_id" "$label" 2>/dev/null || true)"
    if [[ -n "$attachment_output" ]]; then
      printf '%s\n' "$attachment_output"
      return 0
    fi
    log "INFO" "Waiting for the autogenerated DRG attachment for the $label RPC in $region (attempt $attempt/$attempts)."
    sleep "$delay"
  done
  fail "Timed out waiting for the $label RPC $rpc_id to have an autogenerated DRG attachment on DRG $drg_id in region $region."
}

wait_for_bg_pid() {
  local pid="$1"
  local label="$2"
  if ! wait "$pid"; then
    fail "$label failed."
  fi
}

create_region_drg_rpc_workstream() {
  local prefix="$1"
  local label="$2"
  local region="$3"
  local compartment_id="$4"
  local drg_name="$5"
  local rpc_name="$6"
  local out_file="$7"
  local drg_id
  local rpc_id
  log "INFO" "[$label] Creating DRG."
  drg_id="$(oci_raw "$region" network drg create --compartment-id "$compartment_id" --display-name "$drg_name" --query 'data.id')"
  wait_for_field "$region" "drg" "$drg_id" "lifecycle-state" "AVAILABLE"
  log "INFO" "[$label] Creating remote peering connection."
  rpc_id="$(oci_raw "$region" network remote-peering-connection create --compartment-id "$compartment_id" --drg-id "$drg_id" --display-name "$rpc_name" --query 'data.id')"
  wait_for_field "$region" "rpc" "$rpc_id" "lifecycle-state" "AVAILABLE"
  verify_rpc_belongs_to_expected_drg "$region" "$rpc_id" "$drg_id" "$label"
  {
    printf '%s=%q\n' "${prefix}_DRG_ID" "$drg_id"
    printf '%s=%q\n' "${prefix}_RPC_ID" "$rpc_id"
  } >"$out_file"
}

create_region_local_artifacts_workstream() {
  local prefix="$1"
  local label="$2"
  local region="$3"
  local compartment_id="$4"
  local exadata_vcn_id="$5"
  local hub_cidr="$6"
  local hub_vcn_name="$7"
  local hub_drg_rt_name="$8"
  local hub_lpg_rt_name="$9"
  local exadata_lpg_name="${10}"
  local hub_lpg_name="${11}"
  local drg_id="${12}"
  local out_file="${13}"
  local hub_vcn_id
  local hub_default_route_table_id
  local hub_drg_route_table_id
  local hub_lpg_route_table_id
  local exadata_lpg_id
  local hub_lpg_id
  local attachment_payload
  local drg_attachment_id
  local dns_prefix

  dns_prefix="$(printf '%s' "$label" | cut -c1-1)"
  log "INFO" "[$label] Creating hub VCN."
  hub_vcn_id="$(oci_raw "$region" network vcn create \
    --compartment-id "$compartment_id" \
    --cidr-block "$hub_cidr" \
    --display-name "$hub_vcn_name" \
    --dns-label "${dns_prefix}h${RUN_TS:9:6}" \
    --query 'data.id')"
  wait_for_field "$region" "vcn" "$hub_vcn_id" "lifecycle-state" "AVAILABLE"
  hub_default_route_table_id="$(oci_raw "$region" network vcn get --vcn-id "$hub_vcn_id" --query 'data."default-route-table-id"')"

  log "INFO" "[$label] Creating hub route tables."
  hub_drg_route_table_id="$(oci_raw "$region" network route-table create --compartment-id "$compartment_id" --vcn-id "$hub_vcn_id" --display-name "$hub_drg_rt_name" --route-rules '[]' --query 'data.id')"
  hub_lpg_route_table_id="$(oci_raw "$region" network route-table create --compartment-id "$compartment_id" --vcn-id "$hub_vcn_id" --display-name "$hub_lpg_rt_name" --route-rules '[]' --query 'data.id')"

  log "INFO" "[$label] Creating and peering LPGs."
  exadata_lpg_id="$(oci_raw "$region" network local-peering-gateway create --compartment-id "$compartment_id" --vcn-id "$exadata_vcn_id" --display-name "$exadata_lpg_name" --query 'data.id')"
  wait_for_field "$region" "lpg" "$exadata_lpg_id" "lifecycle-state" "AVAILABLE"
  hub_lpg_id="$(oci_raw "$region" network local-peering-gateway create --compartment-id "$compartment_id" --vcn-id "$hub_vcn_id" --display-name "$hub_lpg_name" --query 'data.id')"
  wait_for_field "$region" "lpg" "$hub_lpg_id" "lifecycle-state" "AVAILABLE"
  oci --region "$region" network local-peering-gateway update --local-peering-gateway-id "$hub_lpg_id" --route-table-id "$hub_lpg_route_table_id" --force >/dev/null
  oci --region "$region" network local-peering-gateway connect --local-peering-gateway-id "$hub_lpg_id" --peer-id "$exadata_lpg_id" >/dev/null
  wait_for_field "$region" "lpg" "$hub_lpg_id" "peering-status" "PEERED"
  wait_for_field "$region" "lpg" "$exadata_lpg_id" "peering-status" "PEERED"

  log "INFO" "[$label] Attaching hub VCN to DRG."
  attachment_payload="$(make_tmp_json)"
  create_drg_attachment_payload "$hub_vcn_id" "$attachment_payload"
  drg_attachment_id="$(oci_raw "$region" network drg-attachment create --drg-id "$drg_id" --network-details "file://$attachment_payload" --display-name "${NAME_PREFIX}-${label}-hub-attachment-${RUN_TS}" --query 'data.id')"
  wait_for_field "$region" "drg-attachment" "$drg_attachment_id" "lifecycle-state" "ATTACHED"
  oci --region "$region" network drg-attachment update --drg-attachment-id "$drg_attachment_id" --route-table-id "$hub_drg_route_table_id" --force >/dev/null
  wait_for_attachment_route_table "$region" "$drg_attachment_id" "$hub_drg_route_table_id"

  {
    printf '%s=%q\n' "${prefix}_HUB_VCN_ID" "$hub_vcn_id"
    printf '%s=%q\n' "${prefix}_HUB_DEFAULT_ROUTE_TABLE_ID" "$hub_default_route_table_id"
    printf '%s=%q\n' "${prefix}_HUB_DRG_ROUTE_TABLE_ID" "$hub_drg_route_table_id"
    printf '%s=%q\n' "${prefix}_HUB_LPG_ROUTE_TABLE_ID" "$hub_lpg_route_table_id"
    printf '%s=%q\n' "${prefix}_EXADATA_LPG_ID" "$exadata_lpg_id"
    printf '%s=%q\n' "${prefix}_HUB_LPG_ID" "$hub_lpg_id"
    printf '%s=%q\n' "${prefix}_DRG_ATTACHMENT_ID" "$drg_attachment_id"
  } >"$out_file"
}

configure_region_post_peering_workstream() {
  local prefix="$1"
  local label="$2"
  local region="$3"
  local compartment_id="$4"
  local exadata_vcn_id="$5"
  local local_client_cidr="$6"
  local local_backup_cidr="$7"
  local remote_client_cidr="$8"
  local remote_backup_cidr="$9"
  local exadata_route_table_ids="${10}"
  local hub_drg_route_table_id="${11}"
  local hub_lpg_route_table_id="${12}"
  local hub_default_route_table_id="${13}"
  local hub_lpg_id="${14}"
  local drg_id="${15}"
  local exadata_lpg_id="${16}"
  local rpc_id="${17}"
  local drg_attachment_id="${18}"
  local nsg_name="${19}"
  local allow_ssh="${20}"
  local tcp_listener_port="${21}"
  local tcps_listener_port="${22}"
  local drg_for_rpc="${23}"
  local out_file="${24}"
  local rpc_attachment_info=()
  local rpc_attachment_id
  local rpc_drg_route_table_id
  local route_table_id
  local nsg_id
  local nsg_rules_file

  mapfile -t rpc_attachment_info < <(wait_for_rpc_attachment_to_drg "$region" "$compartment_id" "$drg_for_rpc" "$rpc_id" "$label")
  [[ ${#rpc_attachment_info[@]} -ge 2 ]] || fail "Failed to resolve the $label RPC DRG attachment for RPC $rpc_id after peering."
  rpc_attachment_id="${rpc_attachment_info[0]}"
  rpc_drg_route_table_id="${rpc_attachment_info[1]}"

  log "INFO" "[$label] Updating route tables."
  update_route_table_add_rule "$region" "$hub_drg_route_table_id" "$local_client_cidr" "$hub_lpg_id" "Managed by $DESCRIPTION_TOKEN to local client subnet via ${label} hub LPG"
  update_route_table_add_rule "$region" "$hub_drg_route_table_id" "$local_backup_cidr" "$hub_lpg_id" "Managed by $DESCRIPTION_TOKEN to local backup subnet via ${label} hub LPG"
  update_route_table_add_rule "$region" "$hub_lpg_route_table_id" "$remote_client_cidr" "$drg_id" "Managed by $DESCRIPTION_TOKEN to remote client subnet via ${label} DRG"
  update_route_table_add_rule "$region" "$hub_lpg_route_table_id" "$remote_backup_cidr" "$drg_id" "Managed by $DESCRIPTION_TOKEN to remote backup subnet via ${label} DRG"
  update_route_table_add_rule "$region" "$hub_default_route_table_id" "$local_client_cidr" "$hub_lpg_id" "Managed by $DESCRIPTION_TOKEN to local client subnet via ${label} hub LPG"
  update_route_table_add_rule "$region" "$hub_default_route_table_id" "$local_backup_cidr" "$hub_lpg_id" "Managed by $DESCRIPTION_TOKEN to local backup subnet via ${label} hub LPG"
  update_route_table_add_rule "$region" "$hub_default_route_table_id" "$remote_client_cidr" "$drg_id" "Managed by $DESCRIPTION_TOKEN to remote client subnet via ${label} DRG"
  update_route_table_add_rule "$region" "$hub_default_route_table_id" "$remote_backup_cidr" "$drg_id" "Managed by $DESCRIPTION_TOKEN to remote backup subnet via ${label} DRG"
  for route_table_id in $exadata_route_table_ids; do
    update_route_table_add_rule "$region" "$route_table_id" "$remote_client_cidr" "$exadata_lpg_id" "Managed by $DESCRIPTION_TOKEN to remote client subnet via ${label} LPG"
    update_route_table_add_rule "$region" "$route_table_id" "$remote_backup_cidr" "$exadata_lpg_id" "Managed by $DESCRIPTION_TOKEN to remote backup subnet via ${label} LPG"
  done
  update_drg_route_table_add_rule "$region" "$rpc_drg_route_table_id" "$local_client_cidr" "$drg_attachment_id"
  update_drg_route_table_add_rule "$region" "$rpc_drg_route_table_id" "$local_backup_cidr" "$drg_attachment_id"

  log "INFO" "[$label] Creating NSG."
  nsg_id="$(oci_raw "$region" network nsg create --compartment-id "$compartment_id" --vcn-id "$exadata_vcn_id" --display-name "$nsg_name" --query 'data.id')"
  nsg_rules_file="$(make_tmp_json)"
  create_nsg_rules_file "$remote_client_cidr" "$remote_backup_cidr" "$allow_ssh" "$tcp_listener_port" "$tcps_listener_port" "$nsg_rules_file"
  oci --region "$region" network nsg rules add --nsg-id "$nsg_id" --security-rules "file://$nsg_rules_file" >/dev/null

  {
    printf '%s=%q\n' "${prefix}_RPC_ATTACHMENT_ID" "$rpc_attachment_id"
    printf '%s=%q\n' "${prefix}_RPC_DRG_ROUTE_TABLE_ID" "$rpc_drg_route_table_id"
    printf '%s=%q\n' "${prefix}_NSG_ID" "$nsg_id"
  } >"$out_file"
}

log "INFO" "Starting setup. Config file: $CONFIG_FILE"
log "INFO" "Bundle version: $BUNDLE_VERSION"
require_cmd bash
require_cmd oci
require_cmd python3

load_config
validate_required_config
ALLOW_SSH="$(normalize_bool "${ALLOW_SSH:-false}")"
DB_TCP_LISTENER_PORT="$(normalize_port_or_empty "${DB_TCP_LISTENER_PORT:-}")"
DB_TCPS_LISTENER_PORT="$(normalize_port_or_empty "${DB_TCPS_LISTENER_PORT:-}")"
NAME_PREFIX="$(sanitize_name_prefix "${NAME_PREFIX:-$NAME_PREFIX_DEFAULT}")"
DESCRIPTION_TOKEN="${NAME_PREFIX}-${RUN_TS}"
log "INFO" "Config validation complete."

validate_vcn_belongs_to_compartment "$PRIMARY_REGION" "$PRIMARY_VCN_OCID" "$PRIMARY_COMPARTMENT_OCID" "primary"
validate_vcn_belongs_to_compartment "$STANDBY_REGION" "$STANDBY_VCN_OCID" "$STANDBY_COMPARTMENT_OCID" "standby"
PRIMARY_VCN_CIDRS_JSON="$(oci_json "$PRIMARY_REGION" network vcn get --vcn-id "$PRIMARY_VCN_OCID" --query 'data."cidr-blocks"')"
STANDBY_VCN_CIDRS_JSON="$(oci_json "$STANDBY_REGION" network vcn get --vcn-id "$STANDBY_VCN_OCID" --query 'data."cidr-blocks"')"
log "INFO" "VCN validation complete."

mapfile -t PRIMARY_CLIENT_SUBNET_INFO < <(discover_subnet "$PRIMARY_REGION" "$PRIMARY_COMPARTMENT_OCID" "$PRIMARY_VCN_OCID" "$PRIMARY_CLIENT_SUBNET_CIDR" "primary client")
mapfile -t PRIMARY_BACKUP_SUBNET_INFO < <(discover_subnet "$PRIMARY_REGION" "$PRIMARY_COMPARTMENT_OCID" "$PRIMARY_VCN_OCID" "$PRIMARY_BACKUP_SUBNET_CIDR" "primary backup")
mapfile -t STANDBY_CLIENT_SUBNET_INFO < <(discover_subnet "$STANDBY_REGION" "$STANDBY_COMPARTMENT_OCID" "$STANDBY_VCN_OCID" "$STANDBY_CLIENT_SUBNET_CIDR" "standby client")
mapfile -t STANDBY_BACKUP_SUBNET_INFO < <(discover_subnet "$STANDBY_REGION" "$STANDBY_COMPARTMENT_OCID" "$STANDBY_VCN_OCID" "$STANDBY_BACKUP_SUBNET_CIDR" "standby backup")

PRIMARY_CLIENT_SUBNET_ID="${PRIMARY_CLIENT_SUBNET_INFO[0]}"
PRIMARY_CLIENT_ROUTE_TABLE_ID="${PRIMARY_CLIENT_SUBNET_INFO[1]}"
PRIMARY_BACKUP_SUBNET_ID="${PRIMARY_BACKUP_SUBNET_INFO[0]}"
PRIMARY_BACKUP_ROUTE_TABLE_ID="${PRIMARY_BACKUP_SUBNET_INFO[1]}"
STANDBY_CLIENT_SUBNET_ID="${STANDBY_CLIENT_SUBNET_INFO[0]}"
STANDBY_CLIENT_ROUTE_TABLE_ID="${STANDBY_CLIENT_SUBNET_INFO[1]}"
STANDBY_BACKUP_SUBNET_ID="${STANDBY_BACKUP_SUBNET_INFO[0]}"
STANDBY_BACKUP_ROUTE_TABLE_ID="${STANDBY_BACKUP_SUBNET_INFO[1]}"
PRIMARY_EXADATA_ROUTE_TABLE_IDS=""
PRIMARY_EXADATA_ROUTE_TABLE_IDS="$(append_unique_word "$PRIMARY_EXADATA_ROUTE_TABLE_IDS" "$PRIMARY_CLIENT_ROUTE_TABLE_ID")"
PRIMARY_EXADATA_ROUTE_TABLE_IDS="$(append_unique_word "$PRIMARY_EXADATA_ROUTE_TABLE_IDS" "$PRIMARY_BACKUP_ROUTE_TABLE_ID")"
STANDBY_EXADATA_ROUTE_TABLE_IDS=""
STANDBY_EXADATA_ROUTE_TABLE_IDS="$(append_unique_word "$STANDBY_EXADATA_ROUTE_TABLE_IDS" "$STANDBY_CLIENT_ROUTE_TABLE_ID")"
STANDBY_EXADATA_ROUTE_TABLE_IDS="$(append_unique_word "$STANDBY_EXADATA_ROUTE_TABLE_IDS" "$STANDBY_BACKUP_ROUTE_TABLE_ID")"
log "INFO" "Subnet discovery complete."

mapfile -t RESOLVED_HUB_CIDRS < <(resolve_hub_vcn_cidrs "$PRIMARY_VCN_CIDRS_JSON" "$STANDBY_VCN_CIDRS_JSON" "${PRIMARY_HUB_VCN_CIDR:-}" "${STANDBY_HUB_VCN_CIDR:-}")
PRIMARY_HUB_VCN_CIDR="${RESOLVED_HUB_CIDRS[0]}"
STANDBY_HUB_VCN_CIDR="${RESOLVED_HUB_CIDRS[1]}"
log "INFO" "Using PRIMARY_HUB_VCN_CIDR=$PRIMARY_HUB_VCN_CIDR"
log "INFO" "Using STANDBY_HUB_VCN_CIDR=$STANDBY_HUB_VCN_CIDR"

persist_state_header
persist_state RUN_TS "$RUN_TS"
persist_state CONFIG_FILE "$CONFIG_FILE"
persist_state LOG_FILE "$LOG_FILE"
persist_state NAME_PREFIX "$NAME_PREFIX"
persist_state DESCRIPTION_TOKEN "$DESCRIPTION_TOKEN"
persist_state PRIMARY_REGION "$PRIMARY_REGION"
persist_state PRIMARY_COMPARTMENT_OCID "$PRIMARY_COMPARTMENT_OCID"
persist_state PRIMARY_VCN_OCID "$PRIMARY_VCN_OCID"
persist_state PRIMARY_CLIENT_SUBNET_CIDR "$PRIMARY_CLIENT_SUBNET_CIDR"
persist_state PRIMARY_BACKUP_SUBNET_CIDR "$PRIMARY_BACKUP_SUBNET_CIDR"
persist_state PRIMARY_CLIENT_SUBNET_ID "$PRIMARY_CLIENT_SUBNET_ID"
persist_state PRIMARY_BACKUP_SUBNET_ID "$PRIMARY_BACKUP_SUBNET_ID"
persist_state PRIMARY_EXADATA_ROUTE_TABLE_IDS "$PRIMARY_EXADATA_ROUTE_TABLE_IDS"
persist_state STANDBY_REGION "$STANDBY_REGION"
persist_state STANDBY_COMPARTMENT_OCID "$STANDBY_COMPARTMENT_OCID"
persist_state STANDBY_VCN_OCID "$STANDBY_VCN_OCID"
persist_state STANDBY_CLIENT_SUBNET_CIDR "$STANDBY_CLIENT_SUBNET_CIDR"
persist_state STANDBY_BACKUP_SUBNET_CIDR "$STANDBY_BACKUP_SUBNET_CIDR"
persist_state STANDBY_CLIENT_SUBNET_ID "$STANDBY_CLIENT_SUBNET_ID"
persist_state STANDBY_BACKUP_SUBNET_ID "$STANDBY_BACKUP_SUBNET_ID"
persist_state STANDBY_EXADATA_ROUTE_TABLE_IDS "$STANDBY_EXADATA_ROUTE_TABLE_IDS"
persist_state ALLOW_SSH "$ALLOW_SSH"
persist_state DB_TCP_LISTENER_PORT "$DB_TCP_LISTENER_PORT"
persist_state DB_TCPS_LISTENER_PORT "$DB_TCPS_LISTENER_PORT"
persist_state PRIMARY_HUB_VCN_CIDR "$PRIMARY_HUB_VCN_CIDR"
persist_state STANDBY_HUB_VCN_CIDR "$STANDBY_HUB_VCN_CIDR"
persist_state PRIMARY_REMOTE_DESTINATION_CIDRS "$STANDBY_CLIENT_SUBNET_CIDR $STANDBY_BACKUP_SUBNET_CIDR"
persist_state STANDBY_REMOTE_DESTINATION_CIDRS "$PRIMARY_CLIENT_SUBNET_CIDR $PRIMARY_BACKUP_SUBNET_CIDR"
log "INFO" "State file created: $STATE_FILE"

PRIMARY_HUB_VCN_NAME="${NAME_PREFIX}-primary-hub-vcn-${RUN_TS}"
STANDBY_HUB_VCN_NAME="${NAME_PREFIX}-standby-hub-vcn-${RUN_TS}"
PRIMARY_HUB_DRG_RT_NAME="${NAME_PREFIX}-primary-hub-transit-drg-rt-${RUN_TS}"
PRIMARY_HUB_LPG_RT_NAME="${NAME_PREFIX}-primary-hub-transit-lpg-rt-${RUN_TS}"
STANDBY_HUB_DRG_RT_NAME="${NAME_PREFIX}-standby-hub-transit-drg-rt-${RUN_TS}"
STANDBY_HUB_LPG_RT_NAME="${NAME_PREFIX}-standby-hub-transit-lpg-rt-${RUN_TS}"
PRIMARY_EXADATA_LPG_NAME="${NAME_PREFIX}-primary-exadata-lpg-${RUN_TS}"
PRIMARY_HUB_LPG_NAME="${NAME_PREFIX}-primary-hub-lpg-${RUN_TS}"
STANDBY_EXADATA_LPG_NAME="${NAME_PREFIX}-standby-exadata-lpg-${RUN_TS}"
STANDBY_HUB_LPG_NAME="${NAME_PREFIX}-standby-hub-lpg-${RUN_TS}"
PRIMARY_DRG_NAME="${NAME_PREFIX}-primary-drg-${RUN_TS}"
STANDBY_DRG_NAME="${NAME_PREFIX}-standby-drg-${RUN_TS}"
PRIMARY_RPC_NAME="${NAME_PREFIX}-primary-rpc-${RUN_TS}"
STANDBY_RPC_NAME="${NAME_PREFIX}-standby-rpc-${RUN_TS}"
PRIMARY_NSG_NAME="${NAME_PREFIX}-primary-cross-region-nsg-${RUN_TS}"
STANDBY_NSG_NAME="${NAME_PREFIX}-standby-cross-region-nsg-${RUN_TS}"

PRIMARY_DRG_RPC_ENV="$(make_tmp_env)"
STANDBY_DRG_RPC_ENV="$(make_tmp_env)"
PRIMARY_LOCAL_ENV="$(make_tmp_env)"
STANDBY_LOCAL_ENV="$(make_tmp_env)"
PRIMARY_POST_ENV="$(make_tmp_env)"
STANDBY_POST_ENV="$(make_tmp_env)"

create_region_drg_rpc_workstream "PRIMARY" "primary" "$PRIMARY_REGION" "$PRIMARY_COMPARTMENT_OCID" "$PRIMARY_DRG_NAME" "$PRIMARY_RPC_NAME" "$PRIMARY_DRG_RPC_ENV" &
PRIMARY_DRG_RPC_PID="$!"
create_region_drg_rpc_workstream "STANDBY" "standby" "$STANDBY_REGION" "$STANDBY_COMPARTMENT_OCID" "$STANDBY_DRG_NAME" "$STANDBY_RPC_NAME" "$STANDBY_DRG_RPC_ENV" &
STANDBY_DRG_RPC_PID="$!"
wait_for_bg_pid "$PRIMARY_DRG_RPC_PID" "Primary DRG/RPC workstream"
wait_for_bg_pid "$STANDBY_DRG_RPC_PID" "Standby DRG/RPC workstream"
# shellcheck disable=SC1090
source "$PRIMARY_DRG_RPC_ENV"
# shellcheck disable=SC1090
source "$STANDBY_DRG_RPC_ENV"
persist_state PRIMARY_DRG_ID "$PRIMARY_DRG_ID"
persist_state PRIMARY_RPC_ID "$PRIMARY_RPC_ID"
persist_state STANDBY_DRG_ID "$STANDBY_DRG_ID"
persist_state STANDBY_RPC_ID "$STANDBY_RPC_ID"
log "INFO" "DRGs and RPCs created in parallel."

log "INFO" "Starting background RPC peering monitor."
start_rpc_peering_background "$PRIMARY_REGION" "$PRIMARY_RPC_ID" "$STANDBY_REGION" "$STANDBY_RPC_ID"

create_region_local_artifacts_workstream "PRIMARY" "primary" "$PRIMARY_REGION" "$PRIMARY_COMPARTMENT_OCID" "$PRIMARY_VCN_OCID" "$PRIMARY_HUB_VCN_CIDR" "$PRIMARY_HUB_VCN_NAME" "$PRIMARY_HUB_DRG_RT_NAME" "$PRIMARY_HUB_LPG_RT_NAME" "$PRIMARY_EXADATA_LPG_NAME" "$PRIMARY_HUB_LPG_NAME" "$PRIMARY_DRG_ID" "$PRIMARY_LOCAL_ENV" &
PRIMARY_LOCAL_PID="$!"
create_region_local_artifacts_workstream "STANDBY" "standby" "$STANDBY_REGION" "$STANDBY_COMPARTMENT_OCID" "$STANDBY_VCN_OCID" "$STANDBY_HUB_VCN_CIDR" "$STANDBY_HUB_VCN_NAME" "$STANDBY_HUB_DRG_RT_NAME" "$STANDBY_HUB_LPG_RT_NAME" "$STANDBY_EXADATA_LPG_NAME" "$STANDBY_HUB_LPG_NAME" "$STANDBY_DRG_ID" "$STANDBY_LOCAL_ENV" &
STANDBY_LOCAL_PID="$!"
wait_for_bg_pid "$PRIMARY_LOCAL_PID" "Primary local artifact workstream"
wait_for_bg_pid "$STANDBY_LOCAL_PID" "Standby local artifact workstream"
# shellcheck disable=SC1090
source "$PRIMARY_LOCAL_ENV"
# shellcheck disable=SC1090
source "$STANDBY_LOCAL_ENV"
persist_state PRIMARY_HUB_VCN_ID "$PRIMARY_HUB_VCN_ID"
persist_state PRIMARY_HUB_DEFAULT_ROUTE_TABLE_ID "$PRIMARY_HUB_DEFAULT_ROUTE_TABLE_ID"
persist_state PRIMARY_HUB_DRG_ROUTE_TABLE_ID "$PRIMARY_HUB_DRG_ROUTE_TABLE_ID"
persist_state PRIMARY_HUB_LPG_ROUTE_TABLE_ID "$PRIMARY_HUB_LPG_ROUTE_TABLE_ID"
persist_state PRIMARY_EXADATA_LPG_ID "$PRIMARY_EXADATA_LPG_ID"
persist_state PRIMARY_HUB_LPG_ID "$PRIMARY_HUB_LPG_ID"
persist_state PRIMARY_DRG_ATTACHMENT_ID "$PRIMARY_DRG_ATTACHMENT_ID"
persist_state STANDBY_HUB_VCN_ID "$STANDBY_HUB_VCN_ID"
persist_state STANDBY_HUB_DEFAULT_ROUTE_TABLE_ID "$STANDBY_HUB_DEFAULT_ROUTE_TABLE_ID"
persist_state STANDBY_HUB_DRG_ROUTE_TABLE_ID "$STANDBY_HUB_DRG_ROUTE_TABLE_ID"
persist_state STANDBY_HUB_LPG_ROUTE_TABLE_ID "$STANDBY_HUB_LPG_ROUTE_TABLE_ID"
persist_state STANDBY_EXADATA_LPG_ID "$STANDBY_EXADATA_LPG_ID"
persist_state STANDBY_HUB_LPG_ID "$STANDBY_HUB_LPG_ID"
persist_state STANDBY_DRG_ATTACHMENT_ID "$STANDBY_DRG_ATTACHMENT_ID"
log "INFO" "Per-region local artifacts created in parallel."

wait_for_rpc_peering_background
log "INFO" "DRG peering complete and verified."

configure_region_post_peering_workstream "PRIMARY" "primary" "$PRIMARY_REGION" "$PRIMARY_COMPARTMENT_OCID" "$PRIMARY_VCN_OCID" "$PRIMARY_CLIENT_SUBNET_CIDR" "$PRIMARY_BACKUP_SUBNET_CIDR" "$STANDBY_CLIENT_SUBNET_CIDR" "$STANDBY_BACKUP_SUBNET_CIDR" "$PRIMARY_EXADATA_ROUTE_TABLE_IDS" "$PRIMARY_HUB_DRG_ROUTE_TABLE_ID" "$PRIMARY_HUB_LPG_ROUTE_TABLE_ID" "$PRIMARY_HUB_DEFAULT_ROUTE_TABLE_ID" "$PRIMARY_HUB_LPG_ID" "$PRIMARY_DRG_ID" "$PRIMARY_EXADATA_LPG_ID" "$PRIMARY_RPC_ID" "$PRIMARY_DRG_ATTACHMENT_ID" "$PRIMARY_NSG_NAME" "$ALLOW_SSH" "$DB_TCP_LISTENER_PORT" "$DB_TCPS_LISTENER_PORT" "$PRIMARY_DRG_ID" "$PRIMARY_POST_ENV" &
PRIMARY_POST_PID="$!"
configure_region_post_peering_workstream "STANDBY" "standby" "$STANDBY_REGION" "$STANDBY_COMPARTMENT_OCID" "$STANDBY_VCN_OCID" "$STANDBY_CLIENT_SUBNET_CIDR" "$STANDBY_BACKUP_SUBNET_CIDR" "$PRIMARY_CLIENT_SUBNET_CIDR" "$PRIMARY_BACKUP_SUBNET_CIDR" "$STANDBY_EXADATA_ROUTE_TABLE_IDS" "$STANDBY_HUB_DRG_ROUTE_TABLE_ID" "$STANDBY_HUB_LPG_ROUTE_TABLE_ID" "$STANDBY_HUB_DEFAULT_ROUTE_TABLE_ID" "$STANDBY_HUB_LPG_ID" "$STANDBY_DRG_ID" "$STANDBY_EXADATA_LPG_ID" "$STANDBY_RPC_ID" "$STANDBY_DRG_ATTACHMENT_ID" "$STANDBY_NSG_NAME" "$ALLOW_SSH" "$DB_TCP_LISTENER_PORT" "$DB_TCPS_LISTENER_PORT" "$STANDBY_DRG_ID" "$STANDBY_POST_ENV" &
STANDBY_POST_PID="$!"
wait_for_bg_pid "$PRIMARY_POST_PID" "Primary post-peering workstream"
wait_for_bg_pid "$STANDBY_POST_PID" "Standby post-peering workstream"
# shellcheck disable=SC1090
source "$PRIMARY_POST_ENV"
# shellcheck disable=SC1090
source "$STANDBY_POST_ENV"
persist_state PRIMARY_RPC_ATTACHMENT_ID "$PRIMARY_RPC_ATTACHMENT_ID"
persist_state PRIMARY_RPC_DRG_ROUTE_TABLE_ID "$PRIMARY_RPC_DRG_ROUTE_TABLE_ID"
persist_state PRIMARY_NSG_ID "$PRIMARY_NSG_ID"
persist_state STANDBY_RPC_ATTACHMENT_ID "$STANDBY_RPC_ATTACHMENT_ID"
persist_state STANDBY_RPC_DRG_ROUTE_TABLE_ID "$STANDBY_RPC_DRG_ROUTE_TABLE_ID"
persist_state STANDBY_NSG_ID "$STANDBY_NSG_ID"
log "INFO" "Per-region post-peering routing and NSG configuration completed in parallel."

log "INFO" "Setup finished successfully."
log "INFO" "State file: $STATE_FILE"
log "INFO" "Log file: $LOG_FILE"
